# Generated by Django 4.2.11 on 2024-04-14 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userresetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpassword',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c02dda34-31b1-4f2a-82b9-364c4f38f0f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
