# Generated by Django 4.2.11 on 2024-04-16 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userresetpassword_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpassword',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
