# Generated by Django 4.2.11 on 2024-04-23 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetpassword',
            name='private_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
