# Generated by Django 4.2.11 on 2024-05-07 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_rating_review_rate_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=50)),
                ('our_team_image', models.ImageField(upload_to='our_team/')),
                ('team_title', models.CharField(max_length=50)),
                ('team_body', models.TextField()),
                ('team_person_name', models.CharField(max_length=50)),
                ('team_person_position', models.CharField(max_length=50)),
                ('team_person_facebook', models.CharField(max_length=100)),
                ('team_person_instagram', models.CharField(max_length=100)),
                ('team_person_linkedin', models.CharField(max_length=100)),
                ('team_person_twitter', models.CharField(max_length=100)),
                ('shop_facebook', models.CharField(max_length=100)),
                ('shop_instagram', models.CharField(max_length=100)),
                ('shop_linkedin', models.CharField(max_length=100)),
                ('shop_twitter', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
