# Generated by Django 4.2.11 on 2024-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
